var EventType = {
  FB_SESSION_READY: 1,
  JEWELBAR_SIDE_MENU_TOGGLE: 10,
  JEWELBAR_BACK: 11,
  SEARCH_BAR_ON_SEARCH_START: 20,
  SEARCH_BAR_ON_SEARCH_END: 21,
  SEARCH_BAR_ON_SEARCH_SELECT: 22,
  SIDE_MENU_HOME: 30,
  SIDE_MENU_PROFILE: 31,
  VIEW_PROFILE: 40
};

exports.EventType = EventType;